version: "3.7"

services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: always
    volumes:
      - ./volumes/nodered_data:/data
    ports:
      - "1880:1880"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    volumes:
      - ./volumes/influxdb:/data
    ports:
      - "8086:8086"

  grafana:
    depends_on:
      - influxdb
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - ./volumes/grafana:/data
    ports:
      - "3000:3000"
    environment:
      - GF_USER=admin
      - GF_PASS=admin
